#!/bin/bash
####################
# JUST a SAMPLE. Write your own.
# Sourcing bashrc is good, unless you have a good reason not to.
#################
set +ex

error_generate(){
if ! [ "${exit_code}" == "" ];then
	echo -e '\E[37;44m'"\033[1m${1}\033[0m"
	exit $exit_code
fi
}


source ~/.bashrc

export HTTP_PROXY=10.113.140.187:3128
export HTTPS_PROXY=10.113.140.187:3128
export http_proxy=10.113.140.187:3128
export https_proxy=10.113.140.187:3128
export no_proxy=localhost,127.0.0.1,sandbox.local,lbg.eu-gb.mybluemix.net,lbg.eu-gb.bluemix.net,10.113.140.170,10.113.140.179,10.113.140.187,10.113.140.168,jenkins.sandbox.extranet.group,nexus.sandbox.extranet.group,gerrit.sandbox.extranet.group,sonar.sandbox.extranet.group

export SASS_BINARY_PATH=${SASS_BINARY_PATH:=~/linux-x64-46_binding.node}

npm config delete proxy

npm set progress=false
npm set phantomjs_cdnurl="https://nexus.sandbox.extranet.group/nexus/content/repositories/binaries/phantomjs"
npm set prefix="/usr/local"
npm set registry="https://nexus.sandbox.extranet.group/nexus/content/groups/npm-master"
npm set tmp='~/tmp'

npm config set chromedriver_cdnurl https://nexus.sandbox.extranet.group/nexus/content/sites/binaries/chromedriver

export "PATH=${PATH}:~/tools/:/usr/local/bin:/bin"

